### PR TITLE
Reimpliments Resomi

### PR DESCRIPTION
**Pull request by Kapu1178**
Commit descriptions for commits up to 4b99eac: https://pastebin.com/uSASbPPH

### CODE REVIEW

**Comment by InTheDark4557** [comment]
god, watching the commits is just...a show

**Comment by InTheDark4557** [comment]
mfw Kapu adds Vore

**Comment by InTheDark4557** [comment]
My man Kapu out here suffering with code so we can all have adorable bird things

**Comment by InTheDark4557** [comment]
Kapu just added screaming and a big cock...i'm scared

**Comment by francinum** [comment]
PR will need to be recreated

**Pull request merged**
